### ISSUE TITLE
Multiple files support

### ISSUE THREAD

**Issue by qt-kaneko** [qt-kaneko/macOS-Native-Copy-Paste#2]
- [x] [Find way to add native copy support for multiple files](https://apple.stackexchange.com/a/339436/464271)
- [ ] Find way to add native paste support for multiple files

**Comment by dwiyatci** [comment]
Thank you, very much, for this small yet useful extension, and making this functionality work! :)) I can confirm both copying and pasting multiple files work on macOS.
